### ISSUE TITLE
Getting `ws.send client not found` running locally

### ISSUE THREAD

**Issue by bvkimball** [architect/sandbox#48] opened 2019-08-24 00:17 UTC
**Describe the issue**

I kept getting "ws.send client not found" when running locally.  Linked sandbox to run locally and debug and it looked like [ws.send-sandbox](https://github.com/architect/functions/blob/e1f8bb023072acf654b7eab01d17104729e831fc/src/ws/send-sandbox.js#L16) was sending the body text as base64 encoded string.

see here: https://github.com/architect/sandbox/blob/master/src/http/register-websocket.js#L86

i had to change the handle to parse the body first:

```
app.post("/__arc", function handle(req, res) {
    let buff = Buffer.from(req.body, "base64");
    let body = JSON.parse(buff.toString());
    let client = connections.find(client => body.id === client.id);
...
```

I am running Node12, i couldn't find anything specific to this being a change but it would seem likely that that might be a cause.

I can submit a PR if anyone is having this issue.

**Comment by andybee** [comment] 2019-10-11 12:40
Just realised this is the underlying issue I was experiencing when originally reporting architect/architect#483 and came up with a very similar patch, but placed the logic inside a check to make sure the body was encoded before attempting to decode. I'm experiencing this issue on Node v10.16.

Can't help but think this should potentially be fixed at "source" if possible (in the architect/functions library ws.send function?) as the logic to parse to JSON already exists as middleware in the internal HTTP library within Sandbox, it just filters out base64 encoding. If we could stop it being encoded in the first place, the sandbox would work as it was seemingly designed to.

**Comment by andybee** [comment] 2019-10-11 12:57
I've created #96 which resolves the issue, but as discussed above and on the PR itself, there might be a better way...?

**Comment by ryanblock** [comment] 2019-10-11 17:19
Thanks for this! I'm coming at it fresh, but I'm super familiar with our payloads/encoding stuff, and suspect #96 may fix the symptom but not the cause. Can someone post clear repro steps (and a reduced case repo)?

I'm going to take a look at this (and any other ws related issues) this weekend.

Thanks!

**Comment by andybee** [comment] 2019-10-11 17:50
I'll try and get something together shortly.

**Comment by ryanblock** [comment] 2019-10-11 18:04
Wonderful, thanks! Will move this to the top of my list as soon as you do.

**Comment by andybee** [comment] 2019-10-12 10:02
That took slightly longer than planned, apologies, but hopefully this catches you when you're awake.

Essentially, create/run an Architect project in the local sandbox which uses Web Sockets, and try to post a message to a connected client from inside a function. I've created a repo which demonstrates this:

https://github.com/andybee/arc-ws

Start it up in the sandbox, visit localhost:3333 and click the 'Ping' button which calls the function that attempts to post. On the sandbox console you should see the error `ws.send client not found` because the internal handler has received a base64 encoded body, rather than it hitting the middleware to decode and present an object literal to that function to find the ID.

**Comment by ryanblock** [comment] 2019-10-12 15:50
No worries, thank you for putting this together! Whether it’s merging your PR or putting another fix into place, I’ll be sure to knock it out this weekend. Will let you know if I have any questions.

**Comment by andybee** [comment] 2019-10-12 16:17
I'm hopeful for a 'proper' fix around not encoding the payload in the first place, the repetition of the decode in the middleware and handler felt... meh. But, the PR is there for the potential "time is more valuable than getting it 100% right" scenario.

**Comment by ryanblock** [comment] 2019-10-13 02:13
Question re. this repo: all the functions `const arc = require('@architect/functions');` (except `ws/default`), yet none of these functions have a package.json file. Do you have `@architect/functions` installed globally?

**Comment by ryanblock** [comment] 2019-10-13 04:10
@bvkimball @andybee thanks for your help and patience. This was a bug I inadvertently introduced a while back, not having realized that certain WebSocket requests fell through the same middleware layers that our normal HTTP requests do. When we made the switch to Arc 6, that introduced new logic necessitated by the payload signature change that came along with moving to CloudFormation; those WS requests got caught by this new body encoding logic. It was pretty subtle and I'm bummed that y'all had to dig into (and wait) on this.

While I was in there I also found and knocked out an edge-y bug where custom WS actions may fail. Anyhow, the PR is live here: https://github.com/architect/sandbox/pull/105

Andy, I verified the fix on your repo, but if possible please pull it down and run it symlinked to a real for additional verification. Would like to get this into the next release, which ideally goes out early next week.

Thanks again!

**Comment by andybee** [comment] 2019-10-13 06:28
> Question re. this repo: all the functions `const arc = require('@architect/functions');` (except `ws/default`), yet none of these functions have a package.json file. Do you have `@architect/functions` installed globally?

I do have it installed globally, but not how I prefer to use it now). Presumably this will fail if I push to AWS unless I add a package.json to each function that's using the helpers?

**Comment by ryanblock** [comment] 2019-10-13 07:01
Yep, that’s right!

**Comment by andybee** [comment] 2019-10-13 07:02
@ryanblock Your branch works for me when linking in to my actual project, thanks!

I've added another commit to my [example WS](https://github.com/andybee/arc-ws) repo to add `package.json` to each function, be curious to know if it follows how you expect that to be implemented?

**Comment by ryanblock** [comment] 2019-10-13 07:06
Just checked one function (on my iPad and about to crash) but that looked good.

**Closed** 2019-10-13 21:53 UTC
